# Generated by Django 3.1.12 on 2025-09-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('kcode', models.IntegerField(primary_key=True, serialize=False, verbose_name='분류코드')),
                ('kname', models.CharField(max_length=100, verbose_name='분류명')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('chcode', models.IntegerField(primary_key=True, serialize=False, verbose_name='채널코드')),
                ('chname', models.CharField(max_length=100, verbose_name='채널명')),
            ],
        ),
        migrations.CreateModel(
            name='Customer2018to2022',
            fields=[
                ('ccode', models.IntegerField(primary_key=True, serialize=False, verbose_name='고객코드')),
                ('rcode', models.IntegerField(verbose_name='지역코드')),
                ('name', models.CharField(max_length=100, verbose_name='고객명')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('birth', models.DateField(verbose_name='생년월일')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('datecode', models.IntegerField(verbose_name='날짜코드')),
                ('date', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='날짜')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('quarter', models.IntegerField(verbose_name='분기')),
                ('month', models.IntegerField(verbose_name='월')),
                ('monthname', models.CharField(max_length=100, verbose_name='월(영문)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pcode', models.IntegerField(primary_key=True, serialize=False, verbose_name='제품코드')),
                ('productName', models.CharField(max_length=100, verbose_name='제품명')),
                ('color', models.CharField(max_length=100, verbose_name='색상')),
                ('initPrice', models.IntegerField(verbose_name='원가')),
                ('price', models.IntegerField(verbose_name='단가')),
                ('kcode', models.CharField(max_length=100, verbose_name='제품분류코드')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('kcode', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='제품분류코드')),
                ('kname', models.CharField(max_length=100, verbose_name='제품분류명')),
                ('category', models.IntegerField(verbose_name='분류코드')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('procode', models.IntegerField(primary_key=True, serialize=False, verbose_name='프로모션코드')),
                ('promotion', models.CharField(max_length=100, verbose_name='프로모션')),
                ('salep', models.FloatField(verbose_name='할인율')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('rcode', models.IntegerField(primary_key=True, serialize=False, verbose_name='지역코드')),
                ('sido', models.CharField(max_length=100, verbose_name='시도')),
                ('gugun', models.CharField(max_length=100, verbose_name='구군시')),
                ('region', models.CharField(max_length=100, verbose_name='지역')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, verbose_name='날짜')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('region', models.CharField(max_length=100, verbose_name='지역')),
                ('ccode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer2018to2022')),
                ('chcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.channel')),
                ('pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('procode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.promotion')),
            ],
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['date'], name='app_sales_date_0c0228_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['pcode'], name='app_sales_pcode_i_778111_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['ccode'], name='app_sales_ccode_i_af33b5_idx'),
        ),
    ]
